DELETE FROM cars WHERE id BETWEEN 101 AND 500;

UPDATE public.cars SET brand='Mitsubishi', model='Lancer Evolution' WHERE id=1;
UPDATE public.cars SET brand='Infiniti', model='G' WHERE id=2;
UPDATE public.cars SET brand='Lincoln', model='Town Car' WHERE id=3;
UPDATE public.cars SET brand='Acura', model='RL' WHERE id=4;
UPDATE public.cars SET brand='Lexus', model='GS' WHERE id=5;
UPDATE public.cars SET brand='Honda', model='Accord' WHERE id=6;
UPDATE public.cars SET brand='Chevrolet', model='Suburban 1500' WHERE id=7;
UPDATE public.cars SET brand='Nissan', model='240SX' WHERE id=8;
UPDATE public.cars SET brand='Volkswagen', model='Jetta' WHERE id=9;
UPDATE public.cars SET brand='GMC', model='Terrain' WHERE id=10;
UPDATE public.cars SET brand='Lincoln', model='MKX' WHERE id=11;
UPDATE public.cars SET brand='BMW', model='M6' WHERE id=12;
UPDATE public.cars SET brand='Chrysler', model='Pacifica' WHERE id=13;
UPDATE public.cars SET brand='Volkswagen', model='Eurovan' WHERE id=14;
UPDATE public.cars SET brand='Ford', model='Econoline E350' WHERE id=15;
UPDATE public.cars SET brand='Suzuki', model='Swift' WHERE id=16;
UPDATE public.cars SET brand='Lexus', model='SC' WHERE id=17;
UPDATE public.cars SET brand='Volkswagen', model='Passat' WHERE id=18;
UPDATE public.cars SET brand='Toyota', model='TundraMax' WHERE id=19;
UPDATE public.cars SET brand='Chevrolet', model='Caprice Classic' WHERE id=20;
UPDATE public.cars SET brand='Pontiac', model='Firebird' WHERE id=21;
UPDATE public.cars SET brand='Subaru', model='Loyale' WHERE id=22;
UPDATE public.cars SET brand='Mitsubishi', model='Excel' WHERE id=23;
UPDATE public.cars SET brand='Mercury', model='Grand Marquis' WHERE id=24;
UPDATE public.cars SET brand='Lamborghini', model='MurciĂ©lago' WHERE id=25;
UPDATE public.cars SET brand='Chevrolet', model='Suburban' WHERE id=26;
UPDATE public.cars SET brand='Cadillac', model='XLR' WHERE id=27;
UPDATE public.cars SET brand='Lexus', model='GX' WHERE id=28;
UPDATE public.cars SET brand='Buick', model='Skylark' WHERE id=29;
UPDATE public.cars SET brand='Pontiac', model='Grand Prix' WHERE id=30;
UPDATE public.cars SET brand='Nissan', model='Sentra' WHERE id=31;
UPDATE public.cars SET brand='Mitsubishi', model='Galant' WHERE id=32;
UPDATE public.cars SET brand='Mitsubishi', model='Tundra' WHERE id=33;
UPDATE public.cars SET brand='Volkswagen', model='Touareg' WHERE id=34;
UPDATE public.cars SET brand='Porsche', model='Boxster' WHERE id=35;
UPDATE public.cars SET brand='Mercury', model='Mountaineer' WHERE id=36;
UPDATE public.cars SET brand='BMW', model='M3' WHERE id=37;
UPDATE public.cars SET brand='Mitsubishi', model='GTO' WHERE id=38;
UPDATE public.cars SET brand='Honda', model='Accord' WHERE id=39;
UPDATE public.cars SET brand='Mercedes-Benz', model='SLK-Class' WHERE id=40;
UPDATE public.cars SET brand='Lexus', model='RX Hybrid' WHERE id=41;
UPDATE public.cars SET brand='Volkswagen', model='Tiguan' WHERE id=42;
UPDATE public.cars SET brand='Maybach', model='57S' WHERE id=43;
UPDATE public.cars SET brand='Chevrolet', model='Suburban 2500' WHERE id=44;
UPDATE public.cars SET brand='Ford', model='Explorer' WHERE id=45;
UPDATE public.cars SET brand='Mitsubishi', model='Truck' WHERE id=46;
UPDATE public.cars SET brand='Pontiac', model='GTO' WHERE id=47;
UPDATE public.cars SET brand='Mazda', model='626' WHERE id=48;
UPDATE public.cars SET brand='Cadillac', model='CTS' WHERE id=49;
UPDATE public.cars SET brand='Toyota', model='TundraMax' WHERE id=50;
UPDATE public.cars SET brand='Dodge', model='Ram 2500' WHERE id=51;
UPDATE public.cars SET brand='Mazda', model='Mazda6 Sport' WHERE id=52;
UPDATE public.cars SET brand='Mercury', model='Cougar' WHERE id=53;
UPDATE public.cars SET brand='Chevrolet', model='Camaro' WHERE id=54;
UPDATE public.cars SET brand='Pontiac', model='Bonneville' WHERE id=55;
UPDATE public.cars SET brand='Subaru', model='Baja' WHERE id=56;
UPDATE public.cars SET brand='Jeep', model='Grand Cherokee' WHERE id=57;
UPDATE public.cars SET brand='Mitsubishi', model='i-MiEV' WHERE id=58;
UPDATE public.cars SET brand='Volkswagen', model='New Beetle' WHERE id=59;
UPDATE public.cars SET brand='GMC', model='Yukon' WHERE id=60;
UPDATE public.cars SET brand='Ford', model='E250' WHERE id=61;
UPDATE public.cars SET brand='Subaru', model='Legacy' WHERE id=62;
UPDATE public.cars SET brand='Lexus', model='IS' WHERE id=63;
UPDATE public.cars SET brand='Plymouth', model='Voyager' WHERE id=64;
UPDATE public.cars SET brand='Suzuki', model='Aerio' WHERE id=65;
UPDATE public.cars SET brand='Kia', model='Spectra' WHERE id=66;
UPDATE public.cars SET brand='Lexus', model='ES' WHERE id=67;
UPDATE public.cars SET brand='Toyota', model='Prius Plug-in Hybrid' WHERE id=68;
UPDATE public.cars SET brand='Saab', model='9-5' WHERE id=69;
UPDATE public.cars SET brand='Hyundai', model='Elantra' WHERE id=70;
UPDATE public.cars SET brand='Mitsubishi', model='Montero Sport' WHERE id=71;
UPDATE public.cars SET brand='Nissan', model='Pathfinder' WHERE id=72;
UPDATE public.cars SET brand='Ford', model='Aerostar' WHERE id=73;
UPDATE public.cars SET brand='Audi', model='TT' WHERE id=74;
UPDATE public.cars SET brand='Mazda', model='RX-8' WHERE id=75;
UPDATE public.cars SET brand='Acura', model='CL' WHERE id=76;
UPDATE public.cars SET brand='Mercedes-Benz', model='CLS-Class' WHERE id=77;
UPDATE public.cars SET brand='Ford', model='Ranger' WHERE id=78;
UPDATE public.cars SET brand='Hyundai', model='Accent' WHERE id=79;
UPDATE public.cars SET brand='GMC', model='Yukon XL 2500' WHERE id=80;
UPDATE public.cars SET brand='Kia', model='Sportage' WHERE id=81;
UPDATE public.cars SET brand='Buick', model='Century' WHERE id=82;
UPDATE public.cars SET brand='Audi', model='Q7' WHERE id=83;
UPDATE public.cars SET brand='Ford', model='Taurus' WHERE id=84;
UPDATE public.cars SET brand='Nissan', model='370Z' WHERE id=85;
UPDATE public.cars SET brand='Ford', model='Flex' WHERE id=86;
UPDATE public.cars SET brand='Nissan', model='200SX' WHERE id=87;
UPDATE public.cars SET brand='BMW', model='745' WHERE id=88;
UPDATE public.cars SET brand='Dodge', model='Charger' WHERE id=89;
UPDATE public.cars SET brand='Toyota', model='FJ Cruiser' WHERE id=90;
UPDATE public.cars SET brand='Pontiac', model='Firefly' WHERE id=91;
UPDATE public.cars SET brand='Ford', model='Mustang' WHERE id=92;
UPDATE public.cars SET brand='Chevrolet', model='Lumina' WHERE id=93;
UPDATE public.cars SET brand='Isuzu', model='Amigo' WHERE id=94;
UPDATE public.cars SET brand='Land Rover', model='Range Rover' WHERE id=95;
UPDATE public.cars SET brand='GMC', model='Acadia' WHERE id=96;
UPDATE public.cars SET brand='Cadillac', model='Escalade EXT' WHERE id=97;
UPDATE public.cars SET brand='Audi', model='TT' WHERE id=98;
UPDATE public.cars SET brand='Pontiac', model='Trans Sport' WHERE id=99;
UPDATE public.cars SET brand='Porsche', model='911' WHERE id=100;
