ALTER TYPE TYPE_OF_FUEL RENAME VALUE 'Benzine' TO 'BENZINE';
ALTER TYPE TYPE_OF_FUEL RENAME VALUE 'Diesel' TO 'DIESEL';
ALTER TYPE TYPE_OF_FUEL RENAME VALUE 'Electric' TO 'ELECTRIC';

ALTER TYPE CAR_BODY_TYPE RENAME VALUE 'Coupe' TO 'COUPE';
ALTER TYPE CAR_BODY_TYPE RENAME VALUE 'Sedan' TO 'SEDAN';
ALTER TYPE CAR_BODY_TYPE RENAME VALUE 'Station_Wagon' TO 'STATION_WAGON';
ALTER TYPE CAR_BODY_TYPE RENAME VALUE 'Hatchback' TO 'HATCHBACK';
ALTER TYPE CAR_BODY_TYPE RENAME VALUE 'Cabriolet' TO 'CABRIOLET';